### ISSUE TITLE
support  istio 1.6.7

### ISSUE THREAD

**Issue by pantianying** [solo-io/wasme#146] opened 2020-08-12 08:56 UTC
Error: image webassemblyhub.io/pantianying/add-header:v0.1 not supported by istio version 1.6.7
When can istio 1.6.7 be supported

**Comment by Sodman** [comment] 2020-08-13 21:10
Support for Istio 1.6.x is available in wasme 0.0.24 and higher.

Closing this as a duplicate of https://github.com/solo-io/wasme/issues/126 .

**Closed by Sodman** 2020-08-13 21:10 UTC
